#include "drivers/galaga_hw.h"

#include <algorithm>
#include <cstring>

#include "core/rom_loader.h"

namespace dsp {
namespace {

// Namco/Galaxian-era resistor DAC weights, used across this whole hardware
// family for the base 32-colour hardware palette.
uint8_t rweight3(uint8_t bits) {
    return uint8_t(0x21 * (bits & 1) + 0x47 * ((bits >> 1) & 1) + 0x97 * ((bits >> 2) & 1));
}
uint32_t argb(uint8_t r, uint8_t g, uint8_t b) { return 0xff000000u | (uint32_t(r) << 16) | (uint32_t(g) << 8) | b; }

// Star field seed table: 252 pre-computed (x, y, colour, set) entries,
// reproducing the pseudo-random pattern generated by the real hardware's
// linear-feedback shift register star generator (four interleaved 63-star
// sets). Functional hardware data, not creative content.
struct StarSeed {
    uint16_t x, y;
    uint8_t col, set;
};
// clang-format off
constexpr StarSeed kStarSeeds[252] = {
{0x0085,0x0006,0x35,0},{0x008F,0x0008,0x30,0},{0x00E5,0x001B,0x07,0},{0x0022,0x001C,0x31,0},
{0x00E5,0x0025,0x1D,0},{0x0015,0x0026,0x29,0},{0x0080,0x002D,0x3B,0},{0x0097,0x002E,0x1C,0},
{0x00BA,0x003B,0x05,0},{0x0036,0x003D,0x36,0},{0x0057,0x0044,0x09,0},{0x00CF,0x0044,0x3D,0},
{0x0061,0x004E,0x27,0},{0x0087,0x0064,0x1A,0},{0x00D6,0x0064,0x17,0},{0x000B,0x006C,0x3C,0},
{0x0006,0x006D,0x24,0},{0x0018,0x006E,0x3A,0},{0x00A9,0x0079,0x23,0},{0x008A,0x007B,0x11,0},
{0x00D6,0x0080,0x0C,0},{0x0067,0x0082,0x3F,0},{0x0039,0x0083,0x38,0},{0x0072,0x0083,0x14,0},
{0x00EC,0x0084,0x16,0},{0x008E,0x0085,0x10,0},{0x0020,0x0088,0x25,0},{0x0095,0x008A,0x0F,0},
{0x000E,0x008D,0x00,0},{0x0006,0x0091,0x2E,0},{0x0007,0x0094,0x0D,0},{0x00AE,0x0097,0x0B,0},
{0x0000,0x0098,0x2D,0},{0x0086,0x009B,0x01,0},{0x0058,0x00A1,0x34,0},{0x00FE,0x00A1,0x3E,0},
{0x00A2,0x00A8,0x1F,0},{0x0041,0x00AA,0x0A,0},{0x003F,0x00AC,0x32,0},{0x00DE,0x00AC,0x03,0},
{0x00D4,0x00B9,0x26,0},{0x006D,0x00BB,0x1B,0},{0x0062,0x00BD,0x39,0},{0x00C9,0x00BE,0x18,0},
{0x006C,0x00C1,0x04,0},{0x0059,0x00C3,0x21,0},{0x0060,0x00CC,0x0E,0},{0x0091,0x00CC,0x12,0},
{0x003F,0x00CF,0x06,0},{0x00F7,0x00CF,0x22,0},{0x0044,0x00D0,0x33,0},{0x0034,0x00D2,0x08,0},
{0x00D3,0x00D9,0x20,0},{0x0071,0x00DD,0x37,0},{0x0073,0x00E1,0x2C,0},{0x00B9,0x00E3,0x2F,0},
{0x00A9,0x00E4,0x13,0},{0x00D3,0x00E7,0x19,0},{0x0037,0x00ED,0x02,0},{0x00BD,0x00F4,0x15,0},
{0x000F,0x00F6,0x28,0},{0x004F,0x00F7,0x2B,0},{0x00FB,0x00FF,0x2A,0},
{0x00FE,0x0004,0x3D,1},{0x00C4,0x0006,0x10,1},{0x001E,0x0007,0x2D,1},{0x0083,0x000B,0x1F,1},
{0x002E,0x000D,0x3C,1},{0x001F,0x000E,0x00,1},{0x00D8,0x000E,0x2C,1},{0x0003,0x000F,0x17,1},
{0x0095,0x0011,0x3F,1},{0x006A,0x0017,0x35,1},{0x00CC,0x0017,0x02,1},{0x0000,0x0018,0x32,1},
{0x0092,0x001D,0x36,1},{0x00E3,0x0021,0x04,1},{0x002F,0x002D,0x37,1},{0x00F0,0x002F,0x0C,1},
{0x009B,0x003E,0x06,1},{0x00A4,0x004C,0x07,1},{0x00EA,0x004D,0x13,1},{0x0084,0x004E,0x21,1},
{0x0033,0x0052,0x0F,1},{0x0070,0x0053,0x0E,1},{0x0006,0x0059,0x08,1},{0x0081,0x0060,0x28,1},
{0x0037,0x0061,0x29,1},{0x008F,0x0067,0x2F,1},{0x001B,0x006A,0x1D,1},{0x00BF,0x007C,0x12,1},
{0x0051,0x007F,0x31,1},{0x0061,0x0086,0x25,1},{0x006A,0x008F,0x0D,1},{0x006A,0x0091,0x19,1},
{0x0090,0x0092,0x05,1},{0x003B,0x0096,0x24,1},{0x008C,0x0097,0x0A,1},{0x0006,0x0099,0x03,1},
{0x0038,0x0099,0x38,1},{0x00A8,0x0099,0x18,1},{0x0076,0x00A6,0x20,1},{0x00AD,0x00A6,0x1C,1},
{0x00EC,0x00A6,0x1E,1},{0x0086,0x00AC,0x15,1},{0x0078,0x00AF,0x3E,1},{0x007B,0x00B3,0x09,1},
{0x0027,0x00B8,0x39,1},{0x0088,0x00C2,0x23,1},{0x0044,0x00C3,0x3A,1},{0x00CF,0x00C5,0x34,1},
{0x0035,0x00C9,0x30,1},{0x006E,0x00D1,0x3B,1},{0x00D6,0x00D7,0x16,1},{0x003A,0x00D9,0x2B,1},
{0x00AB,0x00E0,0x11,1},{0x00E0,0x00E2,0x1B,1},{0x006F,0x00E6,0x0B,1},{0x00B8,0x00E8,0x14,1},
{0x00D9,0x00E8,0x1A,1},{0x00F9,0x00E8,0x22,1},{0x0004,0x00F1,0x2E,1},{0x0049,0x00F8,0x26,1},
{0x0010,0x00F9,0x01,1},{0x0039,0x00FB,0x33,1},{0x0028,0x00FC,0x27,1},
{0x00FA,0x0006,0x19,2},{0x00E4,0x0007,0x2D,2},{0x0072,0x000A,0x03,2},{0x0084,0x001B,0x00,2},
{0x00BA,0x001D,0x29,2},{0x00E3,0x0022,0x04,2},{0x00D1,0x0026,0x2A,2},{0x0089,0x0032,0x30,2},
{0x005B,0x0036,0x27,2},{0x0084,0x003A,0x36,2},{0x0053,0x003F,0x0D,2},{0x0008,0x0040,0x1D,2},
{0x0055,0x0040,0x1A,2},{0x00AA,0x0041,0x31,2},{0x00FB,0x0041,0x2B,2},{0x00BC,0x0046,0x16,2},
{0x0093,0x0052,0x39,2},{0x00B9,0x0057,0x10,2},{0x0054,0x0059,0x28,2},{0x00E6,0x005A,0x01,2},
{0x00A7,0x005D,0x1B,2},{0x002D,0x005E,0x35,2},{0x0014,0x0062,0x21,2},{0x0069,0x006D,0x1F,2},
{0x00CE,0x006F,0x0B,2},{0x00DF,0x0075,0x2F,2},{0x00CB,0x0077,0x12,2},{0x004E,0x007C,0x23,2},
{0x004A,0x0084,0x0F,2},{0x0012,0x0086,0x25,2},{0x0068,0x008C,0x32,2},{0x0003,0x0095,0x20,2},
{0x000A,0x009C,0x17,2},{0x005B,0x00A3,0x08,2},{0x005F,0x00A4,0x3E,2},{0x0072,0x00A4,0x2E,2},
{0x00CC,0x00A6,0x06,2},{0x008A,0x00AB,0x0C,2},{0x00E0,0x00AD,0x26,2},{0x00F3,0x00AF,0x0A,2},
{0x0075,0x00B4,0x13,2},{0x0068,0x00B7,0x11,2},{0x006D,0x00C2,0x2C,2},{0x0076,0x00C3,0x14,2},
{0x00CF,0x00C4,0x1E,2},{0x0004,0x00C5,0x1C,2},{0x0013,0x00C6,0x3F,2},{0x00B9,0x00C7,0x3C,2},
{0x0005,0x00D7,0x34,2},{0x0095,0x00D7,0x3A,2},{0x00FC,0x00D8,0x02,2},{0x00E7,0x00DC,0x09,2},
{0x001D,0x00E1,0x05,2},{0x0005,0x00E6,0x33,2},{0x001C,0x00E9,0x3B,2},{0x00A2,0x00ED,0x37,2},
{0x0028,0x00EE,0x07,2},{0x00DD,0x00EF,0x18,2},{0x006D,0x00F0,0x38,2},{0x00A1,0x00F2,0x0E,2},
{0x0074,0x00F7,0x3D,2},{0x0069,0x00F9,0x22,2},{0x003F,0x00FF,0x24,2},
{0x0071,0x0010,0x34,3},{0x00AF,0x0011,0x23,3},{0x00A0,0x0014,0x26,3},{0x0002,0x0017,0x02,3},
{0x004B,0x0019,0x31,3},{0x0093,0x001C,0x0E,3},{0x001B,0x001E,0x25,3},{0x0032,0x0020,0x2E,3},
{0x00EE,0x0020,0x3A,3},{0x0079,0x0022,0x2F,3},{0x006C,0x0023,0x17,3},{0x00BC,0x0025,0x11,3},
{0x0041,0x0029,0x30,3},{0x001C,0x002E,0x32,3},{0x00B9,0x0031,0x01,3},{0x0083,0x0032,0x05,3},
{0x0095,0x003A,0x12,3},{0x000D,0x003F,0x07,3},{0x0020,0x0041,0x33,3},{0x0092,0x0045,0x2C,3},
{0x00D4,0x0047,0x08,3},{0x00A1,0x004B,0x2D,3},{0x00D2,0x004B,0x3B,3},{0x00D6,0x0052,0x24,3},
{0x009A,0x005F,0x1C,3},{0x0016,0x0060,0x3D,3},{0x001A,0x0063,0x1F,3},{0x00CD,0x0066,0x28,3},
{0x00FF,0x0067,0x10,3},{0x0035,0x0069,0x20,3},{0x008F,0x006C,0x04,3},{0x00CA,0x006C,0x2A,3},
{0x005A,0x0074,0x09,3},{0x0060,0x0078,0x38,3},{0x0072,0x0079,0x1E,3},{0x0037,0x007F,0x29,3},
{0x0012,0x0080,0x14,3},{0x0029,0x0082,0x2B,3},{0x0084,0x0098,0x36,3},{0x0032,0x0099,0x37,3},
{0x00BB,0x00A0,0x19,3},{0x003E,0x00A3,0x3E,3},{0x004A,0x00A6,0x1A,3},{0x0029,0x00A7,0x21,3},
{0x009D,0x00B7,0x22,3},{0x006C,0x00B9,0x15,3},{0x000C,0x00C0,0x0A,3},{0x00C2,0x00C3,0x0F,3},
{0x002F,0x00C9,0x0D,3},{0x00D2,0x00CE,0x16,3},{0x00F3,0x00CE,0x0B,3},{0x0075,0x00CF,0x27,3},
{0x001A,0x00D5,0x35,3},{0x0026,0x00D6,0x39,3},{0x0080,0x00DA,0x3C,3},{0x00A9,0x00DD,0x00,3},
{0x00BC,0x00EB,0x03,3},{0x0032,0x00EF,0x1B,3},{0x0067,0x00F0,0x3F,3},{0x00EF,0x00F1,0x18,3},
{0x00A8,0x00F3,0x0C,3},{0x00DE,0x00F9,0x1D,3},{0x002C,0x00FA,0x13,3},
};
// clang-format on

}  // namespace

std::vector<uint8_t> GalagaHw::rotate_cw(const GfxSet& src, int count, int size) {
    std::vector<uint8_t> out(size_t(count) * size_t(size) * size_t(size));
    for (int n = 0; n < count; n++) {
        const uint8_t* s = src.element(n);
        uint8_t* d = &out[size_t(n) * size_t(size) * size_t(size)];
        for (int row = 0; row < size; row++)
            for (int col = 0; col < size; col++)
                d[row * size + col] = s[(size - 1 - col) * size + row];
    }
    return out;
}

GalagaHw::GalagaHw(Game game)
    : game_(game),
      main_cpu_(kCpuClock),
      sub_cpu_(kCpuClock),
      sub2_cpu_(kCpuClock),
      wsg_(kCpuClock),
      io51_(kCpuClock),
      io53_(kCpuClock),
      io54_(kCpuClock) {
    if (game_ == Game::Bosconian) {
        screen_width_ = 285;
        screen_height_ = 224;
    } else {
        screen_width_ = 224;
        screen_height_ = 288;
    }
    framebuffer_.assign(size_t(screen_width_) * size_t(screen_height_), 0xff000000u);

    main_cpu_.set_memory_handlers([this](uint16_t a) { return main_read(a); },
                                  [this](uint16_t a, uint8_t v) { main_write(a, v); });
    sub_cpu_.set_memory_handlers([this](uint16_t a) { return sub_read(a); },
                                 [this](uint16_t a, uint8_t v) { main_write(a, v); });
    sub2_cpu_.set_memory_handlers([this](uint16_t a) { return sub2_read(a); },
                                  [this](uint16_t a, uint8_t v) { main_write(a, v); });
    main_cpu_.set_cycle_handler([this](int cycles) { on_main_cycles(cycles); });

    // 06xx slot 0 -> Namco51xx (coin/inputs), slot 3 -> Namco54xx (sound fx).
    // (Dig Dug instead wires slot 1 to Namco53xx; done in init() per game.)
    Namco06xx::Slot slot51;
    slot51.chip_select = [this](bool a) { io51_.set_chip_select(a); };
    slot51.set_rw = [this](bool r) { io51_.set_rw(r); };
    slot51.write = [this](uint8_t v) { io51_.write(v); };
    slot51.read = [this] { return io51_.read(); };
    bridge_.set_slot(0, slot51);

    Namco06xx::Slot slot54;
    slot54.chip_select = [this](bool a) { io54_.set_chip_select(a); };
    slot54.write = [this](uint8_t v) { io54_.write(v); };
    bridge_.set_slot(3, slot54);

    // In galaga_hw.pas, namco_06xx_nmi pulses the MAIN cpu's NMI line (not
    // the sub CPUs' - those are driven separately off the scanline counter).
    bridge_.set_nmi_callback([this] { main_cpu_.set_nmi(IrqLine::Pulse); });

    io51_.set_input(0, [this] { return uint8_t(in0_ & 0x0f); });
    io51_.set_input(1, [this] { return uint8_t(in0_ >> 4); });
    io51_.set_input(2, [this] { return uint8_t(in1_ & 0x0f); });
    io51_.set_input(3, [this] { return uint8_t(in1_ >> 4); });

    main_cycles_per_line_ = int(kCpuClock / uint32_t(kScanlines * kFramesPerSecond));
}

const char* GalagaHw::title() const {
    switch (game_) {
        case Game::Galaga: return "Galaga";
        case Game::DigDug: return "Dig Dug";
        case Game::Xevious: return "Xevious";
        case Game::SuperXevious: return "Super Xevious";
        case Game::Bosconian: return "Bosconian";
    }
    return "Galaga";
}

// ---------------------------------------------------------------------------
// Loading
// ---------------------------------------------------------------------------

bool GalagaHw::load_galaga(const std::string& rom_path, std::string* error) {
    RomLoader loader;
    if (!loader.open(rom_path, error)) return false;

    const std::vector<RomEntry> main_rom = {
        {"gg1_1b.3p", 0x1000, 0x0000, 0xab036c9f},
        {"gg1_2b.3m", 0x1000, 0x1000, 0xd9232240},
        {"gg1_3.2m", 0x1000, 0x2000, 0x753ce503},
        {"gg1_4b.2l", 0x1000, 0x3000, 0x499fcc76},
    };
    std::vector<uint8_t> main_bytes(0x4000, 0);
    if (!loader.load(main_rom, main_bytes, error)) return false;
    std::copy(main_bytes.begin(), main_bytes.end(), mem_.begin());

    std::vector<uint8_t> sub_bytes(0x1000, 0);
    if (!loader.load({{"gg1_5b.3f", 0x1000, 0, 0xbb5caae3}}, sub_bytes, error)) return false;
    std::copy(sub_bytes.begin(), sub_bytes.end(), sub_rom_.begin());

    std::vector<uint8_t> sub2_bytes(0x1000, 0);
    if (!loader.load({{"gg1_7b.2c", 0x1000, 0, 0xd016686b}}, sub2_bytes, error)) return false;
    std::copy(sub2_bytes.begin(), sub2_bytes.end(), sub2_rom_.begin());

    std::vector<uint8_t> io51_rom, io54_rom;
    if (!loader.try_read("51xx.bin", io51_rom) || !io51_.load_rom(io51_rom, error)) {
        if (error) *error = "namco 51xx MCU ROM (51xx.bin) missing or invalid";
        return false;
    }
    if (!loader.try_read("54xx.bin", io54_rom) || !io54_.load_rom(io54_rom, error)) {
        if (error) *error = "namco 54xx MCU ROM (54xx.bin) missing or invalid";
        return false;
    }

    std::vector<uint8_t> wsg_rom;
    if (!loader.load({{"prom-1.1d", 0x100, 0, 0x7a2815b4}}, wsg_rom, error)) return false;
    wsg_.set_waveform_rom(wsg_rom);

    // Chars: 8x8, 2bpp, nibble-packed with a half-ROM split (see draw code).
    std::vector<uint8_t> char_rom;
    if (!loader.load({{"gg1_9.4l", 0x1000, 0, 0x58b2f47c}}, char_rom, error)) return false;
    {
        GfxLayout layout;
        layout.width = 8;
        layout.height = 8;
        layout.total = 0x100;
        layout.planes = 2;
        layout.char_increment = 16 * 8;
        layout.plane_offsets = {4, 0};
        layout.x_offsets = {8 * 8 + 0, 8 * 8 + 1, 8 * 8 + 2, 8 * 8 + 3, 0, 1, 2, 3};
        layout.y_offsets = {0, 8, 16, 24, 32, 40, 48, 56};
        chars_.decode(layout, char_rom);
        chars_rotated_ = rotate_cw(chars_, layout.total, 8);
    }

    // Sprites: 16x16, 2bpp, same nibble-pack scheme extended to 4 quadrants.
    std::vector<uint8_t> spr_rom;
    if (!loader.load({{"gg1_11.4d", 0x1000, 0, 0xad447c80}, {"gg1_10.4f", 0x1000, 0x1000, 0xdd6f1afc}},
                      spr_rom, error))
        return false;
    {
        GfxLayout layout;
        layout.width = 16;
        layout.height = 16;
        layout.total = 0x80;
        layout.planes = 2;
        layout.char_increment = 64 * 8;
        layout.plane_offsets = {4, 0};
        layout.x_offsets = {0, 1, 2, 3, 8 * 8, 8 * 8 + 1, 8 * 8 + 2, 8 * 8 + 3, 16 * 8, 16 * 8 + 1,
                             16 * 8 + 2, 16 * 8 + 3, 24 * 8, 24 * 8 + 1, 24 * 8 + 2, 24 * 8 + 3};
        layout.y_offsets = {0, 8, 16, 24, 32, 40, 48, 56, 32 * 8, 33 * 8, 34 * 8, 35 * 8, 36 * 8, 37 * 8, 38 * 8, 39 * 8};
        sprites_.decode(layout, spr_rom);
        sprites_rotated_ = rotate_cw(sprites_, layout.total, 16);
    }

    // Palette PROM: base 32 hardware colours + 64 procedural star colours.
    std::vector<uint8_t> prom;
    if (!loader.load({{"prom-5.5n", 0x20, 0, 0x54603c6b},
                       {"prom-4.2n", 0x100, 0x20, 0x59b6edab},
                       {"prom-3.1c", 0x100, 0x120, 0x4a04bb6b}},
                      prom, error))
        return false;
    for (int i = 0; i < 0x20; i++) {
        const uint8_t v = prom[size_t(i)];
        palette_[size_t(i)] = argb(rweight3(v), rweight3(v >> 3), uint8_t(0x47 * ((v >> 6) & 1) + 0x97 * ((v >> 7) & 1)));
    }
    constexpr uint8_t kStarMap[4] = {0x00, 0x47, 0x97, 0xde};
    for (int i = 0; i < 64; i++)
        palette_[size_t(32 + i)] = argb(kStarMap[i & 3], kStarMap[(i >> 2) & 3], kStarMap[(i >> 4) & 3]);
    for (int i = 0; i < 0x100; i++) {
        char_lut_[size_t(i)] = uint8_t(prom[size_t(0x20 + i)] + 0x10);
        tile_lut_[size_t(i)] = prom[size_t(0x120 + i)];
    }
    return true;
}

bool GalagaHw::init(const std::string& rom_path, std::string* error) {
    bool ok = false;
    switch (game_) {
        case Game::Galaga:
            ok = load_galaga(rom_path, error);
            break;
        default:
            if (error) *error = "this game is not implemented in this build yet";
            return false;
    }
    if (!ok) return false;

    reset();
    return true;
}

void GalagaHw::reset() {
    main_cpu_.reset();
    sub_cpu_.reset();
    sub2_cpu_.reset();
    io51_.reset();
    io53_.reset();
    io54_.reset();
    bridge_.reset();
    bridge2_.reset();
    wsg_.reset();

    io51_.set_reset(false);
    io53_.set_reset(false);
    io54_.set_reset(false);
    star_control_.fill(0);
    scrollx_bg_ = scrolly_bg_ = 0;
    scrollx_fg_ = scrolly_fg_ = 0;
    main_irq_ = sub_irq_ = sub2_nmi_ = false;
    sub_held_ = sub2_held_ = true;
    flip_screen_ = false;
    in0_ = in1_ = 0xff;
    in2_ = 0x11;
    for (int i = 0; i < 8; i++) latch_write(i, 0);
}

// ---------------------------------------------------------------------------
// Main/sub CPU memory map (Galaga variant; shared by all games on this HW)
// ---------------------------------------------------------------------------

uint8_t GalagaHw::main_read(uint16_t addr) {
    if (addr <= 0x3fff) return mem_[addr];
    if ((addr >= 0x8000 && addr <= 0x8bff) || (addr >= 0x9000 && addr <= 0x93ff) ||
        (addr >= 0x9800 && addr <= 0x9bff))
        return mem_[addr];
    if (addr >= 0x6800 && addr <= 0x6807) return dip_bits(uint8_t(addr & 7), uint8_t(addr & 7));
    if (addr >= 0x7000 && addr <= 0x70ff) return bridge_.data_read(uint8_t(addr & 0xff));
    if (addr == 0x7100) return bridge_.ctrl_read();
    return 0xff;
}

void GalagaHw::main_write(uint16_t addr, uint8_t value) {
    if (addr <= 0x3fff) return;  // ROM
    if (addr >= 0x6800 && addr <= 0x681f) {
        wsg_.write(addr & 0x1f, value);
        return;
    }
    if (addr >= 0x6820 && addr <= 0x6827) {
        latch_write(addr & 7, value);
        return;
    }
    if (addr >= 0x7000 && addr <= 0x70ff) {
        bridge_.data_write(uint8_t(addr & 0xff), value);
        return;
    }
    if (addr == 0x7100) {
        bridge_.ctrl_write(value);
        return;
    }
    if (addr >= 0x8000 && addr <= 0x87ff) {
        mem_[addr] = value;  // char RAM; redraw is unconditional per frame here
        return;
    }
    if ((addr >= 0x8800 && addr <= 0x8bff) || (addr >= 0x9000 && addr <= 0x93ff) ||
        (addr >= 0x9800 && addr <= 0x9bff)) {
        mem_[addr] = value;
        return;
    }
    if (addr >= 0xa000 && addr <= 0xa005) {
        star_control_[addr & 7] = value;
        return;
    }
    if (addr == 0xa007) {
        flip_screen_ = (value & 1) != 0;
        return;
    }
}

uint8_t GalagaHw::sub_read(uint16_t addr) {
    if (addr <= 0x3fff) return sub_rom_[addr];
    return main_read(addr);
}

uint8_t GalagaHw::sub2_read(uint16_t addr) {
    if (addr <= 0x3fff) return sub2_rom_[addr];
    return main_read(addr);
}

void GalagaHw::latch_write(int bit, uint8_t value) {
    const bool set = (value & 1) != 0;
    switch (bit) {
        case 0:
            main_irq_ = set;
            if (!set) main_cpu_.set_irq(IrqLine::Clear);
            break;
        case 1:
            sub_irq_ = set;
            if (!set) sub_cpu_.set_irq(IrqLine::Clear);
            break;
        case 2:
            sub2_nmi_ = !set;
            break;
        case 3: {
            const bool run = set;
            if (run && sub_held_) sub_cpu_.reset();
            if (run && sub2_held_) sub2_cpu_.reset();
            sub_held_ = !run;
            sub2_held_ = !run;
            break;
        }
        case 5:
            custom_mod_ = uint8_t((custom_mod_ & ~1) | (value & 1));
            break;
        case 6:
            custom_mod_ = uint8_t((custom_mod_ & ~2) | ((value & 1) << 1));
            break;
        case 7:
            custom_mod_ = uint8_t((custom_mod_ & ~4) | ((value & 1) << 2));
            break;
        default:
            break;
    }
}

uint8_t GalagaHw::dip_bits(uint8_t bit, uint8_t /*unused*/) const {
    const uint8_t b0 = uint8_t((dsw_b_ >> bit) & 1);
    const uint8_t b1 = uint8_t((dsw_a_ >> bit) & 1);
    return uint8_t(b0 | (b1 << 1));
}

void GalagaHw::set_dip_switch(int bank, uint8_t value) {
    if (bank == 0) dsw_a_ = value;
    if (bank == 1) dsw_b_ = value;
}

// ---------------------------------------------------------------------------
// Inputs
// ---------------------------------------------------------------------------

void GalagaHw::set_inputs(const MachineInputs& inputs) {
    uint8_t v1 = 0;
    if (inputs.player1.up) v1 |= 0x01;
    if (inputs.player1.right) v1 |= 0x02;
    if (inputs.player1.down) v1 |= 0x04;
    if (inputs.player1.left) v1 |= 0x08;
    if (inputs.player2.up) v1 |= 0x10;
    if (inputs.player2.right) v1 |= 0x20;
    if (inputs.player2.down) v1 |= 0x40;
    if (inputs.player2.left) v1 |= 0x80;
    in1_ = v1;

    uint8_t v0 = 0;
    if (inputs.player1.button1) v0 |= 0x01;
    if (inputs.player2.button1) v0 |= 0x02;
    if (inputs.player1.start) v0 |= 0x04;
    if (inputs.player2.start) v0 |= 0x08;
    if (inputs.coin1) v0 |= 0x10;
    if (inputs.coin2) v0 |= 0x20;
    in0_ = v0;
}

// ---------------------------------------------------------------------------
// Audio
// ---------------------------------------------------------------------------

void GalagaHw::on_main_cycles(int cycles) {
    bridge_.tick(cycles, kCpuClock);

    wsg_accumulator_ += int64_t(cycles) * int64_t(NamcoWsg::kSampleRate);
    while (wsg_accumulator_ >= int64_t(kCpuClock)) {
        wsg_accumulator_ -= int64_t(kCpuClock);
        audio_.push_back(wsg_.update());
    }
}

void GalagaHw::drain_audio(std::vector<int16_t>& out) {
    out.insert(out.end(), audio_.begin(), audio_.end());
    audio_.clear();
}

// ---------------------------------------------------------------------------
// Video: Galaga
// ---------------------------------------------------------------------------

void GalagaHw::draw_star(int set_a, int set_b, int scroll_x, int scroll_y, bool wrap_xy) {
    for (const auto& s : kStarSeeds) {
        if (s.set != set_a && s.set != set_b) continue;
        int x, y;
        if (wrap_xy) {
            y = (s.y + scroll_y) % 256 + 16;
            x = (112 + s.x + scroll_x) % 256;
        } else {
            y = (s.y + scroll_y) & 0xff;
            x = (s.x + scroll_x) & 0xff;
        }
        if (x < 0 || x >= screen_width_ || y < 0 || y >= screen_height_) continue;
        framebuffer_[size_t(y) * size_t(screen_width_) + size_t(x)] = palette_[size_t(32 + s.col)];
    }
}

void GalagaHw::render_galaga() {
    std::fill(framebuffer_.begin(), framebuffer_.end(), palette_[32 + kStarSeeds[0].col] & 0x00000000u);
    std::fill(framebuffer_.begin(), framebuffer_.end(), 0xff000000u);

    if ((star_control_[5] & 1) != 0) {
        const int set_a = star_control_[3] & 1;
        const int set_b = (star_control_[4] & 1) | 2;
        draw_star(set_a, set_b, scrollx_bg_, scrolly_bg_, true);
    }

    // Sprites ($8b80-$8bff attrs/colour, $9380-$93ff pos, $9b80-$9bff attrs2).
    for (int f = 0; f < 0x40; f++) {
        const uint8_t nchar = uint8_t(mem_[0x8b80 + f * 2] & 0x7f);
        const int color = (mem_[0x8b81 + f * 2] & 0x3f) << 2;
        int y = mem_[0x9381 + f * 2] - 40 + 0x100 * (mem_[0x9b81 + f * 2] & 3);
        int x = mem_[0x9380 + f * 2] - 16 - 1;
        const uint8_t atrib = mem_[0x9b80 + f * 2];
        const bool flip_x = (atrib & 2) != 0;
        const bool flip_y = (atrib & 1) != 0;
        // Only the 16x16 single-cell case is common in Galaga; larger
        // composite sprites reuse the same cell four times.
        const uint8_t* px = &sprites_rotated_[size_t(nchar & 0x7f) * 256];
        for (int sy = 0; sy < 16; sy++) {
            const int fy = y + sy;
            if (fy < 0 || fy >= screen_height_) continue;
            const int sy_src = flip_y ? 15 - sy : sy;
            for (int sx = 0; sx < 16; sx++) {
                const uint8_t p = px[sy_src * 16 + (flip_x ? 15 - sx : sx)];
                if (p == 0) continue;
                const int fx = x + sx;
                if (fx < 0 || fx >= screen_width_) continue;
                const uint8_t idx = tile_lut_[size_t(color + p) & 0xff];
                framebuffer_[size_t(fy) * size_t(screen_width_) + size_t(fx)] = palette_[idx & 0x5f];
            }
        }
    }

    // Char layer: 36x28 visible cells over a 32x64 tile RAM grid, drawn
    // straight from tile RAM every frame (no dirty tracking needed here).
    for (int x = 0; x <= 27; x++) {
        for (int y = 0; y <= 35; y++) {
            const int sx = 29 - x;
            const int sy = y - 2;
            int pos;
            if ((sy & 0x20) != 0) pos = sx + ((sy & 0x1f) << 5);
            else pos = sy + (sx << 5);
            if (pos < 0 || pos >= 0x400) continue;
            const int color = (mem_[0x8400 + pos] & 0x3f) << 2;
            const uint8_t nchar = mem_[0x8000 + pos];
            const uint8_t* px = &chars_rotated_[size_t(nchar) * 64];
            for (int py = 0; py < 8; py++) {
                const int fy = y * 8 + py;
                if (fy < 0 || fy >= screen_height_) continue;
                for (int pxi = 0; pxi < 8; pxi++) {
                    const uint8_t p = px[py * 8 + pxi];
                    if (p == 0) continue;
                    const int fx = x * 8 + pxi;
                    if (fx < 0 || fx >= screen_width_) continue;
                    const uint8_t idx = char_lut_[size_t(color + p) & 0xff];
                    framebuffer_[size_t(fy) * size_t(screen_width_) + size_t(fx)] = palette_[idx & 0x5f];
                }
            }
        }
    }
}

void GalagaHw::render_digdug() {}
void GalagaHw::render_bosconian() {}
void GalagaHw::render_xevious() {}

void GalagaHw::run_frame() {
    for (int line = 0; line < kScanlines; line++) {
        main_cpu_.run(main_cycles_per_line_);
        if (!sub_held_) sub_cpu_.run(main_cycles_per_line_);
        if (!sub2_held_) sub2_cpu_.run(main_cycles_per_line_);
        io51_.run(main_cycles_per_line_);
        io53_.run(main_cycles_per_line_);
        io54_.run(main_cycles_per_line_);

        if (line == 63 || line == 191) {
            if (sub2_nmi_) sub2_cpu_.set_nmi(IrqLine::Pulse);
        } else if (line == 223) {
            if (main_irq_) main_cpu_.set_irq(IrqLine::Assert);
            if (sub_irq_) sub_cpu_.set_irq(IrqLine::Assert);
            switch (game_) {
                case Game::Galaga: render_galaga(); break;
                case Game::DigDug: render_digdug(); break;
                case Game::Bosconian: render_bosconian(); break;
                case Game::Xevious:
                case Game::SuperXevious: render_xevious(); break;
            }
        }
    }
}

}  // namespace dsp
