#include "drivers/msx1.h"

#include <algorithm>
#include <cstring>
#include <filesystem>
#include <fstream>

#include "core/rom_loader.h"
#include "cpu/irq_line.h"

namespace dsp {
namespace {
const std::vector<RomEntry> kBiosRom = {{"mpc100bios.rom", 0x8000, 0x0000, 0xa317e6b4}};
const std::array<uint16_t,35> kRunKey0={0x027f,0x02ff,0x04fd,0x04ff,0x04ef,0x04ff,0x02bf,0x02ff,0x03fd,0x03ff,0x06fe,0x02fe,0x06ff,0x02ff,0x03fe,0x03ff,0x02bf,0x02ff,0x05fe,0x05ff,0x06fe,0x017f,0x06ff,0x01ff,0x06fe,0x02fe,0x06ff,0x02ff,0x02fb,0x02ff,0x047f,0x04ff,0x077f,0x07ff,0xffff};
const std::array<uint16_t,13> kRunKey1={0x03fe,0x03ff,0x04fd,0x04ff,0x04ef,0x04ff,0x02bf,0x02ff,0x03fd,0x03ff,0x077f,0x07ff,0xffff};
const std::array<uint16_t,23> kRunKey2={0x047f,0x04ff,0x05fb,0x05ff,0x04f7,0x04ff,0x06fe,0x02fe,0x06ff,0x02ff,0x03fe,0x03ff,0x02bf,0x02ff,0x05fe,0x05ff,0x06fe,0x017f,0x06ff,0x01ff,0x077f,0x07ff,0xffff};

bool read_plain_or_zip_file(const std::string& path,std::vector<uint8_t>& data,size_t max_size,std::string* error){namespace fs=std::filesystem;std::error_code ec;if(fs::is_regular_file(path,ec)){std::ifstream probe(path,std::ios::binary);char magic[4]={};probe.read(magic,4);bool zip=probe.gcount()==4&&magic[0]=='P'&&magic[1]=='K'&&magic[2]==3&&magic[3]==4;if(!zip){probe.clear();probe.seekg(0,std::ios::end);std::streamoff size=probe.tellg();probe.seekg(0,std::ios::beg);if(size<=0){if(error)*error="cannot read "+path;return false;}data.resize(size_t(size));probe.read(reinterpret_cast<char*>(data.data()),size);if(data.size()>max_size)data.resize(max_size);return bool(probe);}}RomLoader loader;if(!loader.open(path,error))return false;data.reserve(max_size);if(!loader.load_first_file(data,error))return false;if(data.size()>max_size)data.resize(max_size);return true;}
}

Msx1::Msx1():z80_(kMainClock),vdp_(1,[this](bool a){on_vdp_interrupt(a);}),ay8910_(kMainClock/2,0.8f){z80_.set_memory_handlers([this](uint16_t a){return read_byte(a);},[this](uint16_t a,uint8_t v){write_byte(a,v);});z80_.set_io_handlers([this](uint16_t p){return read_port(p);},[this](uint16_t p,uint8_t v){write_port(p,v);});z80_.set_cycle_handler([this](int c){on_main_cycles(c);});ay8910_.set_port_handlers([this]{return ay_port_a_read();},[this]{return ay_port_b_read();},nullptr,[this](uint8_t v){ay_port_b_write(v);});ppi_.set_port_handlers([this]{return port_a_read();},[this]{return port_b_read();},nullptr,[this](uint8_t v){port_a_write(v);},nullptr,[this](uint8_t v){port_c_write(v);});}

bool Msx1::init(const std::string& rom_path,std::string* error){RomLoader loader;if(!loader.open(rom_path,error))return false;std::vector<uint8_t> bios(0x8000,0);if(!loader.load(kBiosRom,bios,error))return false;std::copy(bios.begin(),bios.begin()+0x4000,slot_[0][0].mem.begin());std::copy(bios.begin()+0x4000,bios.end(),slot_[0][1].mem.begin());slot_[0][0].rom=slot_[0][1].rom=true;slot_[0][0].ena=slot_[0][1].ena=true;for(int p=0;p<4;++p){slot_[3][p].rom=false;slot_[3][p].ena=true;}warnings_=loader.warnings();reset();return true;}

void Msx1::reset(){z80_.reset();ay8910_.reset();ppi_.reset();vdp_.reset();cartridge_.reset();keypad_.fill(0xff);joystick_={0x3f,0x3f};joy_select_=0;port_a_=0;port_c_=0x7f;last_irq_=false;audio_accumulator_=0;audio_.clear();page_slot_={0,0,0,0};pag_rom_[0]=pag_rom_[1]=true;pag_ena_[0]=pag_ena_[1]=true;for(int p=0;p<4;++p){slot_[2][p].mem.fill(0);slot_[3][p].mem.fill(0);}}

uint8_t Msx1::read_byte(uint16_t address){int p=address>>14;if(!pag_ena_[p])return 0xff;if(page_slot_[p]==1)return cartridge_.read(address);return slot_[page_slot_[p]][p].mem[address&0x3fff];}
void Msx1::write_byte(uint16_t address,uint8_t value){int p=address>>14;if(page_slot_[p]==1){cartridge_.write(address,value);return;}if(pag_rom_[p]||!pag_ena_[p])return;slot_[page_slot_[p]][p].mem[address&0x3fff]=value;}

uint8_t Msx1::read_port(uint16_t port){port&=0xff;switch(port){case 0x98:return vdp_.vram_read();case 0x99:return vdp_.register_read();case 0xa2:return ay8910_.read();case 0xa8:case 0xa9:case 0xaa:case 0xab:return ppi_.read(port&3);default:return 0xff;}}
void Msx1::write_port(uint16_t port,uint8_t value){port&=0xff;switch(port){case 0x98:vdp_.vram_write(value);break;case 0x99:vdp_.register_write(value);break;case 0xa0:ay8910_.control(value);break;case 0xa1:ay8910_.write(value);break;case 0xa8:case 0xa9:case 0xaa:case 0xab:ppi_.write(port&3,value);break;default:break;}}
void Msx1::on_vdp_interrupt(bool a){if(a&&!last_irq_)z80_.set_irq(IrqLine::Hold);last_irq_=a;}
uint8_t Msx1::ay_port_a_read(){return uint8_t(joystick_[joy_select_]|uint8_t(tape_.level()<<1));}
void Msx1::ay_port_b_write(uint8_t v){joy_select_=(v&0x40)>>6;port_b_ay_=v;}
uint8_t Msx1::port_b_read(){return teclado_<10?keypad_[teclado_]:0xff;}
void Msx1::port_a_write(uint8_t v){for(int p=0;p<4;++p){int s=(v>>(p*2))&3;page_slot_[p]=s;pag_rom_[p]=slot_[s][p].rom;pag_ena_[p]=slot_[s][p].ena;}port_a_=v;}
void Msx1::port_c_write(uint8_t v){teclado_=v&0x0f;if(((port_c_^v)&0x10)&&tape_.is_loaded()){bool on=(v&0x10)==0;if(on&&!tape_.is_playing())tape_.play(false);if(!on&&tape_.is_playing())tape_.pause();}port_c_=v;}
void Msx1::on_main_cycles(int cycles){if(tape_.is_playing())tape_.advance(int(double(cycles)*3500000.0/double(kMainClock)));audio_accumulator_+=uint64_t(cycles)*uint64_t(AY8910::kSampleRate);while(audio_accumulator_>=kMainClock){audio_accumulator_-=kMainClock;int32_t s=ay8910_.update();if(port_c_&0x80)s+=3000;if(tape_.is_playing())s+=int32_t(tape_.level())*96;audio_.push_back(int16_t(std::clamp(s,-32768,32767)));}}

bool Msx1::load_media(const std::string& path,std::string* error){std::string l=path;for(char& c:l)c=char(std::tolower(static_cast<unsigned char>(c)));if(l.size()>=4&&((l.size()>=4&&l.compare(l.size()-4,4,".tzx")==0)||(l.size()>=4&&l.compare(l.size()-4,4,".tsx")==0)||(l.size()>=4&&l.compare(l.size()-4,4,".cas")==0)||(l.size()>=4&&l.compare(l.size()-4,4,".wav")==0)))return load_tape(path,error);std::vector<uint8_t> data;if(!read_plain_or_zip_file(path,data,kMaxCartridge,error))return false;if(data.empty()){if(error)*error="empty cartridge";return false;}if(!cartridge_.load(std::move(data),path)){if(error)*error="cannot initialize cartridge mapper";return false;}warnings_.emplace_back(std::string("MSX1 cartridge mapper: ")+cartridge_.name());reset();return true;}

bool Msx1::load_tape(const std::string& path,std::string* error){if(!tape_.load_file(path,error))return false;tape_.stop();start_auto_type(auto_type_key_type_);return true;}
void Msx1::tape_play(){if(!tape_.is_loaded())return;if(tape_.is_paused())tape_.play(false);else tape_.play(true);}void Msx1::tape_stop(){tape_.stop();}
void Msx1::start_auto_type(int k){auto_type_active_=true;auto_type_pos_=0;auto_type_key_type_=k;auto_type_frame_counter_=0;}
void Msx1::auto_type_step(){const uint16_t* t=nullptr;int n=0;switch(auto_type_key_type_){case 0:t=kRunKey0.data();n=int(kRunKey0.size());break;case 1:t=kRunKey1.data();n=int(kRunKey1.size());break;default:t=kRunKey2.data();n=int(kRunKey2.size());break;}if(auto_type_pos_>=n){auto_type_active_=false;return;}uint16_t e=t[auto_type_pos_];if(e==0xffff){auto_type_active_=false;auto_type_pos_=0;return;}keypad_[e>>8]=uint8_t(e);++auto_type_pos_;}
void Msx1::run_frame(){if(auto_type_active_){++auto_type_frame_counter_;if(auto_type_frame_counter_>=int(kFramesPerSecond*0.25+0.5)){auto_type_frame_counter_=0;auto_type_step();}}for(int line=0;line<kScanlines;++line){z80_.run(kCyclesPerLine);vdp_.refresh_ntsc(line);}}

void Msx1::set_inputs(const MachineInputs& inputs){keypad_.fill(0xff);bool r=inputs.key(Key::RightShift);if(inputs.key(Key::Num0))keypad_[0]&=0xfe;if(inputs.key(Key::Num1)&&!r)keypad_[0]&=0xfd;if(inputs.key(Key::Num2)&&!r)keypad_[0]&=0xfb;if(inputs.key(Key::Num3)&&!r)keypad_[0]&=0xf7;if(inputs.key(Key::Num4)&&!r)keypad_[0]&=0xef;if(inputs.key(Key::Num5)&&!r)keypad_[0]&=0xdf;if(inputs.key(Key::Num6))keypad_[0]&=0xbf;if(inputs.key(Key::Num7))keypad_[0]&=0x7f;if(inputs.key(Key::Num8))keypad_[1]&=0xfe;if(inputs.key(Key::Num9))keypad_[1]&=0xfd;if(inputs.key(Key::Semicolon))keypad_[1]&=0xfb;if(inputs.key(Key::Comma))keypad_[1]&=0xef;if(inputs.key(Key::Period))keypad_[1]&=0xdf;if(inputs.key(Key::Slash))keypad_[1]&=0xbf;if(inputs.key(Key::Minus))keypad_[1]&=0x7f;if(inputs.key(Key::Quote))keypad_[2]&=0xfe;if(inputs.key(Key::A))keypad_[2]&=0xbf;if(inputs.key(Key::B))keypad_[2]&=0x7f;if(inputs.key(Key::C))keypad_[3]&=0xfe;if(inputs.key(Key::D))keypad_[3]&=0xfd;if(inputs.key(Key::E))keypad_[3]&=0xfb;if(inputs.key(Key::F))keypad_[3]&=0xf7;if(inputs.key(Key::G))keypad_[3]&=0xef;if(inputs.key(Key::H))keypad_[3]&=0xdf;if(inputs.key(Key::I))keypad_[3]&=0xbf;if(inputs.key(Key::J))keypad_[3]&=0x7f;if(inputs.key(Key::K))keypad_[4]&=0xfe;if(inputs.key(Key::L))keypad_[4]&=0xfd;if(inputs.key(Key::M))keypad_[4]&=0xfb;if(inputs.key(Key::N))keypad_[4]&=0xf7;if(inputs.key(Key::O))keypad_[4]&=0xef;if(inputs.key(Key::P))keypad_[4]&=0xdf;if(inputs.key(Key::Q))keypad_[4]&=0xbf;if(inputs.key(Key::R))keypad_[4]&=0x7f;if(inputs.key(Key::S))keypad_[5]&=0xfe;if(inputs.key(Key::T))keypad_[5]&=0xfd;if(inputs.key(Key::U))keypad_[5]&=0xfb;if(inputs.key(Key::V))keypad_[5]&=0xf7;if(inputs.key(Key::W))keypad_[5]&=0xef;if(inputs.key(Key::X))keypad_[5]&=0xdf;if(inputs.key(Key::Y))keypad_[5]&=0xbf;if(inputs.key(Key::Z))keypad_[5]&=0x7f;if(inputs.key(Key::LeftShift))keypad_[6]&=0xfe;if(inputs.key(Key::LeftCtrl))keypad_[6]&=0xfd;if(inputs.key(Key::CapsLock))keypad_[6]&=0xf7;if(inputs.key(Key::F1))keypad_[6]&=0xdf;if(inputs.key(Key::Num2)&&r)keypad_[6]&=0xbf;if(inputs.key(Key::Num3)&&r)keypad_[6]&=0x7f;if(inputs.key(Key::Num4)&&r)keypad_[7]&=0xfe;if(inputs.key(Key::Num5)&&r)keypad_[7]&=0xfd;if(inputs.key(Key::Escape))keypad_[7]&=0xfb;if(inputs.key(Key::Tab))keypad_[7]&=0xf7;if(inputs.key(Key::Backspace))keypad_[7]&=0xdf;if(inputs.key(Key::Enter))keypad_[7]&=0x7f;if(inputs.key(Key::Space))keypad_[8]&=0xfe;if(inputs.key(Key::Left))keypad_[8]&=0xef;if(inputs.key(Key::Up))keypad_[8]&=0xdf;if(inputs.key(Key::Down))keypad_[8]&=0xbf;if(inputs.key(Key::Right))keypad_[8]&=0x7f;joystick_={0x3f,0x3f};const InputState* ps[2]={&inputs.player1,&inputs.player2};for(int p=0;p<2;++p){const auto& q=*ps[p];uint8_t j=0x3f;if(q.up)j&=0xfe;if(q.down)j&=0xfd;if(q.left)j&=0xfb;if(q.right)j&=0xf7;if(q.button1)j&=0xef;if(q.button2)j&=0xdf;joystick_[size_t(p)]=j;}}
void Msx1::set_dip_switch(int,uint8_t){}
void Msx1::drain_audio(std::vector<int16_t>& out){out.insert(out.end(),audio_.begin(),audio_.end());audio_.clear();}
} // namespace dsp
