#!/usr/bin/env python3
"""Writes a C file with ROMs, disks, tapes and cartridges as arrays, to compile
them into dsp (like galagino's romconv). The executable then starts that game
when it is run without arguments; ROMs given on the command line still work.

    python3 tools/embed_media.py -o embedded_media.c --game blockout --rom blockout.zip
    python3 tools/embed_media.py -o embedded_media.c --game c64 --rom roms/c64/ --tape game.prg
    python3 tools/embed_media.py -o embedded_media.c --game spectrum128 --rom spec128.zip \\
        --tape manic.tzx --arg=--scale --arg=2

--rom takes a zip, a single ROM file or a directory (embedded with all its
files). --tape, --disk and --cart can be repeated. Normally used through CMake:
    cmake -S . -B build -DDSP_EMBED_GAME=blockout -DDSP_EMBED_ROM=/path/blockout.zip
"""

import argparse
import os
import re
import sys

BYTES_PER_LINE = 20


def c_string(text):
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"') + '"'


def collect(rom, media):
    """(relative path in the embedded tree, file on disk) pairs and the ROM argument."""
    files = []
    if os.path.isdir(rom):
        base = os.path.basename(os.path.normpath(rom)) or "rom"
        for root, dirs, names in os.walk(rom):
            dirs.sort()
            for name in sorted(names):
                full = os.path.join(root, name)
                rel = os.path.relpath(full, rom).replace(os.sep, "/")
                files.append((f"{base}/{rel}", full))
        rom_arg = f"@/{base}"
    elif os.path.isfile(rom):
        files.append((os.path.basename(rom), rom))
        rom_arg = "@/" + os.path.basename(rom)
    else:
        sys.exit(f"embed_media: ROM path not found: {rom}")
    media_args = []
    for option, path in media:
        if not os.path.isfile(path):
            sys.exit(f"embed_media: {option} file not found: {path}")
        rel = "media/" + os.path.basename(path)
        if any(r == rel for r, _ in files):
            sys.exit(f"embed_media: two media files are called {os.path.basename(path)}")
        files.append((rel, path))
        media_args += [option, "@/" + rel]
    return files, rom_arg, media_args


def write_c(out, game, files, rom_arg, media_args, extra):
    args = ["--game", game, rom_arg] + media_args + extra
    total = sum(os.path.getsize(p) for _, p in files)
    with open(out, "w", newline="\n") as f:
        f.write("/* Generated by tools/embed_media.py: do not edit.\n")
        f.write(f" * --game {game}, {len(files)} file(s), {total} bytes. */\n")
        f.write('#include "core/embedded_media.h"\n\n')
        for index, (rel, path) in enumerate(files):
            with open(path, "rb") as src:
                data = src.read()
            f.write(f"/* {rel} ({len(data)} bytes) */\n")
            f.write(f"static const unsigned char dsp_embed_{index}[{max(len(data), 1)}] = {{\n")
            if not data:
                f.write("0\n")
            for start in range(0, len(data), BYTES_PER_LINE):
                chunk = data[start:start + BYTES_PER_LINE]
                f.write(",".join(str(b) for b in chunk) + ",\n")
            f.write("};\n\n")
        f.write("const DspEmbeddedFile dsp_embedded_files[] = {\n")
        for index, (rel, path) in enumerate(files):
            f.write(f"    {{{c_string(rel)}, dsp_embed_{index}, {os.path.getsize(path)}u}},\n")
        f.write("};\n")
        f.write(f"const size_t dsp_embedded_file_count = {len(files)};\n\n")
        f.write("const char* const dsp_embedded_args[] = {\n")
        for a in args:
            f.write(f"    {c_string(a)},\n")
        f.write("    0\n};\n")
    return total


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-o", "--output", required=True, help="C file to write")
    parser.add_argument("--game", required=True, help="--game name to start (e.g. blockout, c64)")
    parser.add_argument("--rom", required=True, help="ROM set: zip, single file or directory")
    parser.add_argument("--tape", action="append", default=[], help="tape/snapshot to load (repeatable)")
    parser.add_argument("--disk", action="append", default=[], help="disk image to load (repeatable)")
    parser.add_argument("--cart", action="append", default=[], help="cartridge to load (repeatable)")
    parser.add_argument("--arg", action="append", default=[],
                        help="extra command-line argument, one per --arg (e.g. --arg=--dip --arg=1:0x6f)")
    args = parser.parse_args()
    if not re.fullmatch(r"[A-Za-z0-9_.+-]+", args.game):
        sys.exit(f"embed_media: odd game name: {args.game}")
    media = [("--tape", p) for p in args.tape] + [("--disk", p) for p in args.disk] + \
            [("--cart", p) for p in args.cart]
    files, rom_arg, media_args = collect(args.rom, media)
    out_dir = os.path.dirname(os.path.abspath(args.output))
    os.makedirs(out_dir, exist_ok=True)
    tmp = args.output + ".tmp"
    total = write_c(tmp, args.game, files, rom_arg, media_args, args.arg)
    os.replace(tmp, args.output)
    print(f"embed_media: wrote {args.output} ({len(files)} file(s), {total} bytes)")


if __name__ == "__main__":
    main()
