#!/usr/bin/env python3
"""Generates src/drivers/computers/ql_vkb_data.inc: Sinclair QL keyboard.

The picture is the photo tools/ql_keyboard.jpg, embedded byte for byte (the
JPEG file itself, decoded at run time); nothing is redrawn. This script only
adds the key table: the tile of every key, measured on the photo from the
grooves between the tiles (rows at y = 138/211/284/357/430/503, columns
listed below, in photo pixels), so clicks land on the key under the mouse,
and the crop that leaves out the red backdrop.

usage: gen_ql_vkb.py out.inc [photo.jpg]
"""
import sys

from PIL import Image

import numpy as np

photo = sys.argv[2] if len(sys.argv) > 2 else "tools/ql_keyboard.jpg"
data = open(photo, "rb").read()
# The machine stands on a red backdrop: show only its bounding box (the
# emulator keys out the red still visible around the outline).
rgb = np.asarray(Image.open(photo).convert("RGB")).astype(int)
red = (rgb[..., 0] - np.maximum(rgb[..., 1], rgb[..., 2])) > 90
ys, xs = np.nonzero(~red)
CROP_X, CROP_Y = int(xs.min()), int(ys.min())
W, H = int(xs.max()) + 1 - CROP_X, int(ys.max()) + 1 - CROP_Y

ROWS = [138, 211, 284, 357, 430, 503]
INSET = 3   # stay inside the grooves


def m(row, mask):
    return row * 8 + (mask.bit_length() - 1)


keys = []


def add(code, flags, x1, row, x2, name):
    keys.append((code, flags, (x1 + INSET - CROP_X, ROWS[row] + INSET - CROP_Y, x2 - INSET - CROP_X,
                               ROWS[row + 1] - INSET - CROP_Y), name))


def row_keys(row, edges, names_codes):
    for (name, code, flags), x1, x2 in zip(names_codes, edges, edges[1:]):
        add(code, flags, x1, row, x2, name)


def k(name, code, flags=0):
    return (name, code, flags)


# F1-F5 column.
for r, (name, code) in enumerate([("F1", m(0, 0x02)), ("F2", m(0, 0x08)), ("F3", m(0, 0x10)), ("F4", m(0, 0x01)),
                                  ("F5", m(0, 0x20))]):
    add(code, 0, 72, r, 142, name)

row_keys(0, [168, 239, 311, 385, 458, 533, 607, 682, 757, 829, 903, 976, 1050, 1124, 1198, 1273],
         [k("ESC", m(1, 0x08)), k("1", m(4, 0x08)), k("2", m(6, 0x02)), k("3", m(4, 0x02)), k("4", m(0, 0x40)),
          k("5", m(0, 0x04)), k("6", m(6, 0x04)), k("7", m(0, 0x80)), k("8", m(6, 0x01)), k("9", m(5, 0x01)),
          k("0", m(6, 0x20)), k("-", m(5, 0x20)), k("=", m(3, 0x20)), k("£", m(2, 0x20)), k("\\", m(1, 0x20))])
row_keys(1, [168, 274, 347, 421, 496, 570, 645, 720, 793, 867, 939, 1013, 1086, 1160],
         [k("TABULATE", m(5, 0x08)), k("Q", m(6, 0x08)), k("W", m(5, 0x02)), k("E", m(6, 0x10)),
          k("R", m(5, 0x10)), k("T", m(6, 0x40)), k("Y", m(5, 0x40)), k("U", m(6, 0x80)), k("I", m(5, 0x04)),
          k("O", m(5, 0x80)), k("P", m(4, 0x20)), k("[", m(3, 0x01)), k("]", m(2, 0x01))])
row_keys(2, [168, 293, 366, 440, 514, 588, 663, 738, 812, 884, 957, 1030, 1103],
         [k("CAPS LOCK", m(3, 0x02)), k("A", m(4, 0x10)), k("S", m(3, 0x08)), k("D", m(4, 0x40)),
          k("F", m(3, 0x10)), k("G", m(3, 0x40)), k("H", m(4, 0x04)), k("J", m(4, 0x80)), k("K", m(3, 0x04)),
          k("L", m(4, 0x01)), k(";", m(3, 0x80)), k("'", m(2, 0x80))])
# ENTER: L-shaped tile, one key wide on row 2 and wider on row 3.
add(m(1, 0x01), 0, 1160, 1, 1234, "ENTER (upper)")
add(m(1, 0x01), 0, 1103, 2, 1234, "ENTER")
row_keys(3, [168, 329, 402, 477, 550, 626, 700, 774, 847, 921, 994, 1067, 1234],
         [k("SHIFT (left)", m(7, 0x01), 1), k("Z", m(2, 0x02)), k("X", m(7, 0x08)), k("C", m(2, 0x08)),
          k("V", m(7, 0x10)), k("B", m(2, 0x10)), k("N", m(7, 0x40)), k("M", m(2, 0x40)), k(",", m(7, 0x80)),
          k(".", m(2, 0x04)), k("/", m(7, 0x20)), k("SHIFT (right)", m(7, 0x01), 1)])
row_keys(4, [168, 294, 365, 438, 956, 1029, 1104, 1233],
         [k("CTRL", m(7, 0x02), 1), k("LEFT", m(1, 0x02)), k("RIGHT", m(1, 0x10)), k("SPACE", m(1, 0x40)),
          k("UP", m(1, 0x04)), k("DOWN", m(1, 0x80)), k("ALT", m(7, 0x04), 1)])

with open(sys.argv[1], "w") as f:
    f.write("// Generated by tools/gen_ql_vkb.py, do not edit.\n")
    f.write("// Sinclair QL keyboard: the photo tools/ql_keyboard.jpg (JPEG bytes, unmodified) and the\n")
    f.write("// key tiles measured on it; key codes are IPC matrix row * 8 + bit.\n")
    f.write("// Shown area: the machine's bounding box in the photo, red backdrop keyed out.\n")
    f.write(f"constexpr int kQlVkbCropX = {CROP_X};\nconstexpr int kQlVkbCropY = {CROP_Y};\n")
    f.write(f"constexpr int kQlVkbWidth = {W};\nconstexpr int kQlVkbHeight = {H};\n")
    f.write("const unsigned char kQlVkbJpeg[] = {\n")
    for i in range(0, len(data), 24):
        f.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",\n")
    f.write("};\n")
    f.write("// code, flags (1 modifier), tile rect.\n")
    f.write("const VkbKeyDef kQlVkbKeys[] = {\n")
    for code, flags, (x1, y1, x2, y2), name in keys:
        name = name.replace("\\", "backslash")  # a trailing \ would continue the comment
        f.write(f"    {{{code}, {flags}, {x1}, {y1}, {x2}, {y2}}},  // {name}\n")
    f.write("};\n")
print(f"{len(keys)} keys, photo cropped to {W}x{H} at ({CROP_X},{CROP_Y}), {len(data)} bytes")
