#!/usr/bin/env python3
"""Generates src/drivers/computers/atari_st_vkb_data.inc from Hataroid.

Hataroid (https://github.com/squalldc/hataroid, GPLv2) ships its on-screen
Atari ST keyboard as a gzipped 1024x1024 RGBA texture (VirtKBTex*.c) plus a
key table (VirtKBDefs.c). This script keeps the 768x256 keyboard picture
(sprite "vkbd") as zlib-compressed RGB and the ST keys that live on it.

usage: gen_st_vkb.py <hataroid>/Projects/Hataroid/src/main/jni/hataroid/src out.inc
"""
import gzip
import re
import sys
import zlib

src_dir, out_path = sys.argv[1], sys.argv[2]


def texture(name):
    text = open(f"{src_dir}/{name}").read()
    body = text[text.index("{") + 1:text.index("};")]
    raw = gzip.decompress(bytes(int(x, 16) for x in re.findall(r"0x([0-9a-fA-F]{2})", body)))
    rgb = bytearray()
    for y in range(256):
        row = raw[y * 1024 * 4:(y * 1024 + 768) * 4]
        for x in range(768):
            rgb += row[x * 4:x * 4 + 3]
    return zlib.compress(bytes(rgb), 9)


defs = open(f"{src_dir}/VirtKBDefs.c").read()
keys = []
pat = re.compile(r'\{ (VKB_KEY_\w+), "((?:[^"\\]|\\.)*)", \{[^}]*\}, (-?\d+), (-?\d+), (-?\d+), (0x[0-9a-f]+), '
                 r'\{ ([-\d, ]+) \}, ([A-Z_|]+),')
for m in pat.finditer(defs):
    name, desc, _cfg, _scut, _sort, code, v, flags = m.groups()
    code = int(code, 16)
    v = [int(x) for x in v.split(",")]
    if code == 0xff or "HOLDKEY" in flags:
        continue
    if not ("STKEY" in flags or "STFNKEY" in flags):
        continue
    if max(v[1], v[3], v[5], v[7]) >= 256:
        continue  # quick-key sprites outside the keyboard picture
    poly = "POLY" in flags
    mod = "MODKEY" in flags
    keys.append((name, desc, code, poly, mod, v))

with open(out_path, "w") as out:
    out.write("// Generated by tools/gen_st_vkb.py from Hataroid (GPLv2), do not edit.\n")
    out.write("// Keyboard picture: 768x256 RGB, zlib.\n")
    for var, tex in (("kVkbPictureUk", "VirtKBTex.c"),):
        data = texture(tex)
        out.write(f"const unsigned char {var}[] = {{\n")
        for i in range(0, len(data), 24):
            out.write("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",\n")
        out.write("};\n")
    out.write("// name, ST scancode, polygon?, modifier?, rect (x1,y1,x2,y2) or quad (4 points).\n")
    out.write("const VkbKey kVkbKeys[] = {\n")
    for name, desc, code, poly, mod, v in keys:
        out.write(f'    {{"{desc}", 0x{code:02x}, {str(poly).lower()}, {str(mod).lower()}, '
                  f'{{{", ".join(str(x) for x in v)}}}}},  // {name}\n')
    out.write("};\n")
print(len(keys), "keys")
