// Verifies SpectrumTape's new WAV/CSW/PZX readers by synthesizing a small,
// self-made pulse train (a pilot tone + a couple of bits) in each format and
// checking it parses and plays through to completion. None of this touches
// or reproduces any real/commercial tape image - every byte here is
// generated by this file.
#include <cstdio>
#include <cstring>
#include <vector>

#include "machine/spectrum_tape.h"

using namespace dsp;

namespace {

void put_u32(std::vector<uint8_t>& v, uint32_t x) {
    v.push_back(uint8_t(x));
    v.push_back(uint8_t(x >> 8));
    v.push_back(uint8_t(x >> 16));
    v.push_back(uint8_t(x >> 24));
}
void put_u16(std::vector<uint8_t>& v, uint16_t x) {
    v.push_back(uint8_t(x));
    v.push_back(uint8_t(x >> 8));
}

// A short, arbitrary pulse train: ten pilot pulses then two "bit" pulses -
// enough to exercise pause/finish handling without a real loader.
std::vector<uint32_t> SamplePulses() {
    std::vector<uint32_t> pulses;
    for (int i = 0; i < 10; i++) pulses.push_back(2168);
    pulses.push_back(855);
    pulses.push_back(1710);
    return pulses;
}

bool RunTape(const char* label, std::vector<uint8_t> data) {
    SpectrumTape tape;
    std::string error;
    if (!tape.load_from_memory(std::move(data), &error)) {
        std::printf("%s: LOAD FAILED: %s\n", label, error.c_str());
        return false;
    }
    tape.set_playing(true);
    int frames = 0;
    while (!tape.finished() && frames < 5000) {
        tape.advance(3500000 / 50);  // one 50Hz frame's worth of T states
        frames++;
    }
    std::printf("%s: blocks=%zu finished=%d frames=%d\n", label, tape.block_count(), tape.finished(),
                frames);
    return tape.finished();
}

}  // namespace

int main() {
    bool ok = true;

    // --- WAV: 16-bit mono PCM square wave matching SamplePulses(). ---
    {
        const uint32_t sample_rate = 44100;
        std::vector<int16_t> samples;
        bool level = false;
        for (uint32_t pulse_t_states : SamplePulses()) {
            const uint32_t n = uint32_t(double(pulse_t_states) * sample_rate / 3500000.0) + 1;
            for (uint32_t i = 0; i < n; i++) samples.push_back(level ? 20000 : -20000);
            level = !level;
        }
        std::vector<uint8_t> wav;
        wav.insert(wav.end(), {'R', 'I', 'F', 'F'});
        put_u32(wav, uint32_t(36 + samples.size() * 2));
        wav.insert(wav.end(), {'W', 'A', 'V', 'E', 'f', 'm', 't', ' '});
        put_u32(wav, 16);
        put_u16(wav, 1);   // PCM
        put_u16(wav, 1);   // mono
        put_u32(wav, sample_rate);
        put_u32(wav, sample_rate * 2);
        put_u16(wav, 2);
        put_u16(wav, 16);
        wav.insert(wav.end(), {'d', 'a', 't', 'a'});
        put_u32(wav, uint32_t(samples.size() * 2));
        for (int16_t s : samples) put_u16(wav, uint16_t(s));
        ok &= RunTape("WAV", wav);
    }

    // --- CSW v2, uncompressed RLE. ---
    {
        std::vector<uint8_t> csw;
        const char sig[] = "Compressed Square Wave";
        csw.insert(csw.end(), sig, sig + 23);
        csw.push_back(0x1a);
        csw.push_back(2);  // major
        csw.push_back(0);  // minor
        put_u32(csw, 44100);
        csw.push_back(0);  // total pulses (low byte of dword, rest below)
        csw.push_back(0);
        csw.push_back(0);
        csw.push_back(0);
        csw.push_back(1);  // compression: 1 = RLE only
        csw.push_back(1);  // initial polarity
        csw.push_back(0);  // header extension length
        for (uint32_t pulse_t_states : SamplePulses()) {
            const uint32_t n = uint32_t(double(pulse_t_states) * 44100.0 / 3500000.0) + 1;
            if (n < 256) {
                csw.push_back(uint8_t(n));
            } else {
                csw.push_back(0);
                put_u32(csw, n);
            }
        }
        ok &= RunTape("CSW", csw);
    }

    // --- PZX: PULS with a mix of plain and repeated entries, then a tiny
    // DATA block (2 bytes' worth of bits), then STOP. ---
    {
        std::vector<uint8_t> pzx;
        pzx.insert(pzx.end(), {'P', 'Z', 'X', 'T'});
        put_u32(pzx, 4);
        put_u32(pzx, 1);  // format version, packed as the Pascal does (major.minor bytes + reserved)

        std::vector<uint8_t> puls;
        put_u16(puls, 0x8000 | 9);  // repeat: 9 pulses of...
        put_u16(puls, 2168);
        put_u16(puls, 855);  // one more plain pulse
        pzx.insert(pzx.end(), {'P', 'U', 'L', 'S'});
        put_u32(pzx, uint32_t(puls.size()));
        pzx.insert(pzx.end(), puls.begin(), puls.end());

        std::vector<uint8_t> data;
        put_u32(data, 16);  // 16 bits
        data.push_back(0);  // initial pulse level byte
        data.push_back(0);  // tail-pulse-and-bit-count high bits (none used here)
        put_u16(data, 0);   // tail pulse length: none
        put_u16(data, 855);   // pulse length for bit '0'
        put_u16(data, 1710);  // pulse length for bit '1'
        data.push_back(0xa5);
        data.push_back(0x5a);
        pzx.insert(pzx.end(), {'D', 'A', 'T', 'A'});
        put_u32(pzx, uint32_t(data.size()));
        pzx.insert(pzx.end(), data.begin(), data.end());

        pzx.insert(pzx.end(), {'S', 'T', 'O', 'P'});
        put_u32(pzx, 2);
        put_u16(pzx, 0);

        ok &= RunTape("PZX", pzx);
    }

    // --- TZX with a $18 (embedded CSW) block and a $19 (generalized data,
    // 2-symbol alphabet) block. ---
    {
        std::vector<uint8_t> tzx;
        const char magic[] = "ZXTape!\x1a";
        tzx.insert(tzx.end(), magic, magic + 8);
        tzx.push_back(1);
        tzx.push_back(20);

        // $18: CSW recording, RLE, uncompressed.
        std::vector<uint8_t> csw_body;
        put_u32(csw_body, 0);       // pause (ms)
        put_u32(csw_body, 44100);   // sample rate
        csw_body.push_back(1);      // compression: RLE
        csw_body.push_back(0);      // flags
        put_u16(csw_body, uint16_t(SamplePulses().size()));  // pulse count (unused by the reader)
        csw_body.push_back(0);      // extension length
        for (uint32_t pulse_t_states : SamplePulses()) {
            const uint32_t n = uint32_t(double(pulse_t_states) * 44100.0 / 3500000.0) + 1;
            csw_body.push_back(n < 256 ? uint8_t(n) : 0);
            if (n >= 256) put_u32(csw_body, n);
        }
        tzx.push_back(0x18);
        put_u32(tzx, uint32_t(csw_body.size()));
        tzx.insert(tzx.end(), csw_body.begin(), csw_body.end());

        // $19: generalized data, 2-symbol alphabet, 8 bits of payload.
        std::vector<uint8_t> gen_body;
        put_u16(gen_body, 0);  // pause (ms)
        put_u32(gen_body, 0);  // TOTP (no pilot/sync symbols)
        gen_body.push_back(0); gen_body.push_back(0);  // NPP, ASP
        put_u32(gen_body, 8);  // TOTD: 8 bits
        gen_body.push_back(2);  // NPD: up to 2 pulses per data symbol
        gen_body.push_back(2);  // ASD: 2 symbols
        gen_body.push_back(0); put_u16(gen_body, 855); put_u16(gen_body, 0);    // symbol 0
        gen_body.push_back(0); put_u16(gen_body, 1710); put_u16(gen_body, 0);   // symbol 1
        gen_body.push_back(0xa5);  // 8 bits of payload
        tzx.push_back(0x19);
        put_u32(tzx, uint32_t(gen_body.size()));
        tzx.insert(tzx.end(), gen_body.begin(), gen_body.end());

        ok &= RunTape("TZX $18+$19", tzx);
    }

    std::printf(ok ? "ALL OK\n" : "SOME FAILED\n");
    return ok ? 0 : 1;
}
